### ISSUE TITLE
数据集请求

### ISSUE THREAD

**Issue by cqg99** [jiankang1991/Challenge_ZhongKeXingTu5_Sea_Ice#2]
作者好，这个比赛已经关闭了，想问一下可以提供一下数据集吗？

**Comment by jiankang1991** [comment]
@cqg99 比赛只提供了训练数据：https://drive.google.com/file/d/1XO7tBKiVHCrtpRMZ2yl9G9bxp1xearBE/view?usp=drive_link

**Comment by cqg99** [comment]
非常感谢作者，我已经提交了谷歌云盘的访问许可的申请了，麻烦给通过一下吧

**Comment by jiankang1991** [comment]
我修改了Access权限，你再看一下

**Comment by cqg99** [comment]
OK啦，非常感谢
